# Generated by Django 6.0.5 on 2026-07-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked_user',
            new_name='liked_users',
        ),
    ]
